### ISSUE TITLE
Linux-Drivers Issue (ArchLinux)

### ISSUE THREAD

**Issue by hitmanof44th** [accesio/linux-drivers#1]
using arch linux version 4.20 to install accesio linux-drivers causes the system to not be able to boot

the card was installed and detected 
lspci | grep ACC
02:04.0 Unassigned class [ff00]: ACCES I/O Products, Inc. PCIe-IIRO-16 Isolated Digital / Relay Output Card

once the drivers are installed the system would not boot

**Comment by jdolanIV** [comment]
@hitmanof44th ,
Did you get support for this issue?
